# Generated by Django 4.2.26 on 2025-11-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("prediction", models.CharField(blank=True, max_length=20, null=True)),
                ("box_x", models.IntegerField(blank=True, null=True)),
                ("box_y", models.IntegerField(blank=True, null=True)),
                ("box_w", models.IntegerField(blank=True, null=True)),
                ("box_h", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
